// AI Service for Quiz Generation using Gemini API

const GEMINI_API_KEY = import.meta.env.VITE_GEMINI_API_KEY

export async function generateQuizWithAI({ topic, numQuestions, difficulty, questionType }) {
    if (!GEMINI_API_KEY) {
        throw new Error('GEMINI_API_KEY not configured. Please add VITE_GEMINI_API_KEY to your .env file.')
    }

    const difficultyDescriptions = {
        beginner: 'basic concepts suitable for beginners',
        intermediate: 'moderate complexity for learners with some knowledge',
        advanced: 'challenging questions for advanced learners'
    }

    const prompt = `Generate exactly ${numQuestions} ${questionType.replace('_', ' ')} quiz questions about "${topic}".

Difficulty level: ${difficulty} (${difficultyDescriptions[difficulty]})

Return ONLY a valid JSON array with this exact structure (no markdown, no code blocks, just raw JSON):
[
  {
    "question_text": "The question here?",
    "question_type": "${questionType}",
    "points": 1,
    "order_index": 0,
    "options": [
      { "option_text": "Option A text", "is_correct": false },
      { "option_text": "Option B text", "is_correct": true },
      { "option_text": "Option C text", "is_correct": false },
      { "option_text": "Option D text", "is_correct": false }
    ]
  }
]

Rules:
- Each question must have exactly 4 options
- Exactly one option must be correct (is_correct: true)
- Make questions educational and accurate about the topic "${topic}"
- order_index should increment from 0
- Return ONLY the JSON array, no other text`

    try {
        const response = await fetch(
            `https://generativelanguage.googleapis.com/v1beta/models/gemini-2.0-flash:generateContent?key=${GEMINI_API_KEY}`,
            {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({
                    contents: [{ parts: [{ text: prompt }] }],
                    generationConfig: {
                        temperature: 0.7,
                        maxOutputTokens: 8192,
                    }
                })
            }
        )

        if (!response.ok) {
            const errorData = await response.json().catch(() => null)
            console.error('Gemini API error:', errorData)
            if (response.status === 400) {
                throw new Error('Invalid request to AI API. Please check your API key.')
            } else if (response.status === 403) {
                throw new Error('API key is invalid or expired. Please get a new key from https://aistudio.google.com/app/apikey')
            } else if (response.status === 429) {
                throw new Error('Too many requests. Please wait a moment and try again.')
            }
            throw new Error(errorData?.error?.message || 'Failed to generate quiz from AI')
        }

        const data = await response.json()
        const textContent = data.candidates?.[0]?.content?.parts?.[0]?.text

        if (!textContent) {
            throw new Error('No content generated by AI')
        }

        // Parse the JSON from the response (clean up any markdown if present)
        let cleanedContent = textContent.trim()
        if (cleanedContent.startsWith('```json')) {
            cleanedContent = cleanedContent.slice(7)
        }
        if (cleanedContent.startsWith('```')) {
            cleanedContent = cleanedContent.slice(3)
        }
        if (cleanedContent.endsWith('```')) {
            cleanedContent = cleanedContent.slice(0, -3)
        }
        cleanedContent = cleanedContent.trim()

        const questions = JSON.parse(cleanedContent)

        return {
            title: `Quiz: ${topic}`,
            description: `AI-generated ${difficulty} quiz about ${topic} with ${numQuestions} questions.`,
            difficulty,
            estimated_minutes: Math.ceil(numQuestions * 1.5),
            questions
        }
    } catch (error) {
        console.error('Error generating quiz:', error)
        throw error
    }
}
